image: docker:20.10.0

build:
  only:
    - branches
  services:
    - docker:20.10.0-dind
  script:
    - tag=$CI_REGISTRY_IMAGE:$(echo $CI_COMMIT_REF_NAME | cut -d'.' -f 1)
    - apk add --update docker
    - docker login
      --username gitlab-ci-token
      --password $CI_JOB_TOKEN $CI_REGISTRY
    - docker build
      --force-rm
      --tag $tag
      --build-arg REPO_USER=gitlab-ci-token 
      --build-arg REPO_TOKEN=${CI_JOB_TOKEN}
      --build-arg http_proxy=$http_proxy
      --build-arg https_proxy=$https_proxy
      .
    - docker push
      $tag
    - docker rmi
      --force
      $tag
